// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nanoflowcommons.proxies;

public enum GeocodingProvider
{
	Google("9c97da6e-8472-465d-af32-b16a3ab050c1"),
	Geocodio("dba115ca-ecc9-4fa4-95ea-bd53c126f741"),
	LocationIQ("ebd759e4-5168-45d1-b0a2-5d157ce4db8d"),
	MapQuest("bf6e2004-63d9-4213-842f-0f0c9ab8a1fa");

	private final java.lang.String i18nCaptionKey;
	
	private GeocodingProvider(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
