// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datawidgets.proxies;

public enum Filter_Operators
{
	contains("cb3e0610-af9d-4849-a5c7-d7e0a3dda5c8"),
	startsWith("163ce641-eddf-4278-b9dc-e24fc20c89c6"),
	endsWith("e32746cb-cd57-4b8e-96a7-76462d2187af"),
	between("b207c20a-44d3-4aa0-b306-03a4a6e5b348"),
	greater("b94801d9-2761-4368-a7cb-c7065d88b9bf"),
	greaterEqual("4cb37d88-7cca-475e-9d8e-df6afecd901b"),
	equal("6ddb0f99-0420-485c-87a3-a698079bb5a5"),
	notEqual("93b3bd1a-ee46-4296-8969-35e606eeba23"),
	smaller("6e4ee8de-318e-4764-afe3-d73b57d778d7"),
	smallerEqual("f48bdf59-2df6-4c90-88bb-3dec3d96f3dc"),
	empty("02804cfb-644b-436c-af7d-538ceb605db0"),
	notEmpty("b9abf148-3be3-491c-ab4e-3d6b07ccb029");

	private final java.lang.String i18nCaptionKey;
	
	private Filter_Operators(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
