// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datawidgets.proxies;

public enum Filter_Operators
{
	contains("0a581f0b-0ffc-4e9f-94b9-478c6f9e2fb8"),
	startsWith("e503d6fe-a4c2-4f02-9e06-47d4f6bb7de1"),
	endsWith("24454bfa-9a7c-45c9-a365-11c0664b9cf2"),
	between("84fd0ed0-49d3-4499-8e5d-d77e6b35b6c3"),
	greater("d8614f2b-beba-437d-9acb-72eb1c2e80b2"),
	greaterEqual("e8fa4e64-c574-4154-b07d-f4a733aec099"),
	equal("55dc1f61-cbcc-449e-b04a-98019ed31858"),
	notEqual("dc7789aa-4de0-4366-b2b7-8defc815dfc1"),
	smaller("3e714a95-23cf-4b42-ab46-ffe3c8819181"),
	smallerEqual("80b9bd95-bdd6-4707-9338-ec05da1ee610"),
	empty("2cafecac-8c29-41c5-9865-bab7ab8eb695"),
	notEmpty("f9a1ebf5-4479-4472-8223-2c0edd1e529f");

	private final java.lang.String i18nCaptionKey;
	
	private Filter_Operators(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
