// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datawidgets.proxies;

public enum Filter_Operators
{
	contains("f31c4e50-576e-4608-89e3-263c0d747128"),
	startsWith("9dc79f7f-6736-4729-a0bd-5594dcbeb15b"),
	endsWith("7211379b-14e7-4b65-b435-d482a4204fa4"),
	between("efe51630-9473-438e-94cc-36c921ca4006"),
	greater("7870edf2-5192-4a0f-aec7-d4be2a74110e"),
	greaterEqual("cd34a65b-2111-4d33-9e8b-0637f9822575"),
	equal("6fdf3607-0bfb-4d28-9622-bed5c8df479e"),
	notEqual("459dc64e-ab79-4206-a787-f853494f8eb0"),
	smaller("66da290c-2f42-4e4a-9a2e-7dbaca05043e"),
	smallerEqual("53f365b6-8222-4526-b73f-53026a614fa7"),
	empty("1edfc4ac-90f0-4ddd-a658-f7146e316f25"),
	notEmpty("974fb9c5-5a46-4863-b09d-10fb67bb257d");

	private final java.lang.String i18nCaptionKey;
	
	private Filter_Operators(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
